### PR TITLE
added a setting default_size

### PR DESCRIPTION
**Pull request by ReanGD**
Implement - #10

### CODE REVIEW

**Comment by simonzack** [comment]
Thanks.

I tested it out, and the default window size appeared to be a very thin horizontal strip.

Do you think it's reasonable to have the default be maximized?

**Comment by ReanGD** [comment]
In tiling window managers, a maximized window looks like a broken one. It hides all the windows on the screen. This may interfere with the use of this application. I would prefer to use the default e.g. 800x600 size. But this is your project, I will do what you think is better.

**Comment by simonzack** [comment]
Ok sure 800x600 is fine ig.

**Comment by ReanGD** [comment]
Fixed

**Pull request merged**
